### ISSUE TITLE
Error when trying to execute ApiClient.ConsoleApp

### ISSUE THREAD

**Issue by RandyLyne** [Digi-Key/ApiClient.V3#2]
This is what i get in the console window. The only changes ive made is to include my client id and secret in the apiclient.config file.

map.ExeConfigFilename C:\Users\rlyne\Dropbox\VCS.Net\Digikey Lookup\Digikey Lookup\ApiClient.V3-master\apiclient.config
   ------------ [ ApiClientSettings ] -------------
     ClientId            : [client id]
     ClientSecret        : [client secret]
     RedirectUri         : https://localhost:44300/Home/FinishAuth
     AccessToken         :
     RefreshToken        :
     ExpirationDateTime  : 1/1/0001 12:00:00 AM
   ---------------------------------------------

Press any key to exit...
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ApiClient.OAuth2.OAuth2Helpers.<RefreshTokenAsync>d__3.MoveNext() in C:\Users\rlyne\Dropbox\VCS.Net\Digikey Lookup\Digikey Lookup\ApiClient.V3-master\ApiClient\OAuth2\OAuth2Helpers.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ApiClient.OAuth2.OAuth2Service.<RefreshTokenAsync>d__8.MoveNext() in C:\Users\rlyne\Dropbox\VCS.Net\Digikey Lookup\Digikey Lookup\ApiClient.V3-master\ApiClient\OAuth2\OAuth2Service.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ApiClient.ConsoleApp.Program.<CallKeywordSearch>d__2.MoveNext() in C:\Users\rlyne\Dropbox\VCS.Net\Digikey Lookup\Digikey Lookup\ApiClient.V3-master\ApiClient.ConsoleApp\Program.cs:line 51

**Comment by RandyLyne** [comment]
Fixed by placing "ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;" into "public async Task<OAuth2AccessToken> RefreshTokenAsync(string code)" in OAuth2Helper.cs

**Comment by RandyLyne** [comment]
Please update fix main code.

**Comment by michael-block** [comment]
This is now merged in master..
